# Generated by Django 2.2.11 on 2023-10-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.Author'),
        ),
    ]
